development:
  adapter: mysql
  database: "realalehunter_development"
  host: localhost
  username: root
  password: 

test: &TEST
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: mysql
  database: "real_ale_hunter_production"
  host: localhost
  username: matt
  password: c3038135cdzvc4

cucumber:
  <<: *TEST
  
old_site:
  adapter: mysql
  database: realalehunter
  username: root
  password:
  host: localhost
  
phpbb_database_development:  
  adapter: mysql
  database: realalehunter_forum
  username: root
  password:
  host: localhost
  
  
phpbb_database_test: &PHPBB_TEST
  adapter: mysql
  database: realalehunter_forum
  username: root
  password:
  host: localhost
  
phpbb_database_cucumber: 
  <<: *PHPBB_TEST
  
phpbb_database_production:  
  adapter: mysql
  database: realalehunter_forum
  username: matt
  password: c3038135cdzvc4
  host: localhost
