development:
  adapter: mysql
  database: "realalehunter_development"
  host: localhost
  username: root
  password: 

test: &TEST
  adapter: mysql
  database: realalehunter_test
  host: localhost
  username: root
  password:

production:
  adapter: mysql
  database: "real_ale_hunter_production"
  host: localhost
  username: web
  password: Hs984hdyNNk297G

cucumber:
  <<: *TEST
  
old_site:
  adapter: mysql
  database: realalehunter
  username: root
  password:
  host: localhost
  
phpbb_database_development:  
  adapter: mysql
  database: realalehunter_forum
  username: root
  password:
  host: localhost
  
  
phpbb_database_test: &PHPBB_TEST
  adapter: mysql
  database: realalehunter_forum
  username: root
  password:
  host: localhost
  
phpbb_database_cucumber: 
  <<: *PHPBB_TEST
  
phpbb_database_production:  
  adapter: mysql
  database: realalehunter_forum_2
  username: matt
  password: c3038135cdzvc4
  host: localhost
