development:
  adapter: mysql2
  database: "realalehunter_development"
  host: localhost
  username: root
  password: 

test: &TEST
  adapter: mysql2
  database: realalehunter_test
  host: localhost
  username: root
  password:

production:
  adapter: mysql2
  database: "real_ale_hunter_production"
  host: localhost
  username: web
  password: Hs984hdyNNk297G

cucumber:
  <<: *TEST
