development:
  adapter: mysql
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test: &TEST
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000

cucumber:
  <<: *TEST
  
old_site:
  adapter: mysql
  database: realalehunter
  username: root
  password:
  host: localhost
  
phpbb_database_development:  
  adapter: mysql
  database: realalehunter_forum
  username: root
  password:
  host: localhost
  
  
phpbb_database_test: &PHPBB_TEST
  adapter: mysql
  database: realalehunter_forum
  username: root
  password:
  host: localhost
  
phpbb_database_cucumber: 
  <<: *PHPBB_TEST
  
phpbb_database_production:  
  adapter: mysql
  database: realalehunter_forum
  username: root
  password:
  host: localhost
